import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
import { auth } from "@/auth";
import { Toaster } from "@/components/ui/sonner";
import { BaseNavbar } from "@/components/base-navbar";
import { AuthProvider } from "@/components/auth-provider";
import "./globals.css";
import { NewUserMenu } from "@/components/auth/new-user-menu";
import { Navbar } from "@/app/(protected)/_components/navbar";
import { ModeToggle } from "@/components/theme-toggle";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <AuthProvider>
      <html lang="en">
        <body className={inter.className}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Toaster />
            <div className="flex flex-row items-center justify-around w-full">
              <BaseNavbar />
              <ModeToggle />
              {!session ? <NewUserMenu /> : <Navbar />}
            </div>
            {children}
          </ThemeProvider>
        </body>
      </html>
    </AuthProvider>
  );
}
