import type { Metadata } from 'next';
import Header from '@/app/components/Header/Header';
import '@/app/globals.css';

import dbConnect from '@/app/lib/dbConnect';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  await dbConnect(); // connect to db

  return (
    <html lang="en">
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
