export const wldb = [
  {
    id: "asdfhakslh",
    name: "TextWidget",
    path: "@/app/(protected)/_components/widgets/text-widget.tsx",
    version: "1.0.0",
    order: 1,
    description: "Simple widget for render text",
    widgetData: {
      text: "example text message",
      tAlign: "center",
      tValign: "center",
      fSize: "20px",
      fColor: "black",
      fStyle: "normal",
      fWeight: "normal",
      fFamily: "Arial",
      bColor: "transparent",
    },
  },
  {
    id: "o3274jesfds",
    name: "ImageWidget",
    path: "@/app/(protected)/_components/widgets/image-widget.tsx",
    version: "1.0.0",
    order: 2,
    description: "Simple widget for upload and render single image",
    widgetData: {
      imgSrc: "/path/to/image.png",
      tAlign: "center",
      tValign: "center",
      fSize: "20px",
      fColor: "black",
      fStyle: "normal",
      fWeight: "normal",
      fFamily: "Arial",
      bColor: "transparent",
    },
  },
  {
    id: "lbgnmglbn",
    name: "TextWidget",
    path: "@/app/(protected)/_components/widgets/text-widget.tsx",
    version: "1.0.0",
    order: 3,
    description: "Simple widget for render text",
    widgetData: {
      text: "example text message",
      tAlign: "center",
      tValign: "center",
      fSize: "20px",
      fColor: "black",
      fStyle: "normal",
      fWeight: "normal",
      fFamily: "Arial",
      bColor: "transparent",
    },
  },
];
