export const enabledWidgets = [
  {
    id: "",
    inviteId: "",
    widgetId: "title-widget-1-0-0",
    order: 0,
    name: "TitleWidget",
    displayName: "Title",
    file: "title-widget",
    version: "1.0.0",
    description: "Simple widget for show names",
    widgetData: {
      nameSeparator: " + ",
      tAlign: "center",
      tValign: "center",
      fSize: "20px",
      fColor: "black",
      fStyle: "normal",
      fWeight: "normal",
      fFamily: "Arial",
      bColor: "transparent",
    },
  },
  {
    id: "",
    inviteId: "",
    widgetId: "text-widget-1-0-0",
    order: 0,
    name: "TextWidget",
    displayName: "Text",
    file: "text-widget",
    version: "1.0.0",
    description: "Simple widget for render text",
    widgetData: {
      text: "example text message",
      tAlign: "center",
      tValign: "center",
      fSize: "20px",
      fColor: "black",
      fStyle: "normal",
      fWeight: "normal",
      fFamily: "Arial",
      bColor: "transparent",
    },
  },
  {
    id: "",
    inviteId: "",
    widgetId: "image-widget-1-0-0",
    order: 0,
    name: "ImageWidget",
    displayName: "Image",
    file: "image-widget",
    version: "1.0.0",
    description: "Simple widget for upload and render single image",
    widgetData: {
      imgSrc: "/path/to/image.png",
      tAlign: "center",
      tValign: "center",
      fSize: "20px",
      fColor: "black",
      fStyle: "normal",
      fWeight: "normal",
      fFamily: "Arial",
      bColor: "transparent",
    },
  },
];
